version: "2"
services:
  ldap_a:
    environment:
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_DOMAIN: "clontarf.umm"
      LDAP_ORGANISATION: "Double of Science"
      LDAP_REPLICATION: "true"
      LDAP_REPLICATION_HOSTS: "PYTHON2BASH:['ldap://ldap_a','ldap://ldap_b']"
      TCP_PORTS: 389
    image: osixia/openldap
  ldap_b:
    environment:
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_DOMAIN: "clontarf.umm"
      LDAP_ORGANISATION: "Double of Science"
      LDAP_REPLICATION: "true"
      LDAP_REPLICATION_HOSTS: "PYTHON2BASH:['ldap://ldap_a','ldap://ldap_b']"
      TCP_PORTS: 389
    image: osixia/openldap
  load_balancer:
    environment:
      MODE: "tcp"
    image: dockercloud/haproxy
    links:
      - ldap_a
      - ldap_b
    ports:
      - "3889:389"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
