version: "2"
services:
  ldap:
    environment:
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_DOMAIN: "clontarf.umm"
      LDAP_ORGANISATION: "Double of Science"
    image: osixia/openldap
    ports:
      - "3889:389"
